[axial_scanning]
exposure_time_for_reflection_finding = 0.05
reflection_threshold_value = 5000.0
step_distance_um_for_reflection_finding = 10
max_search_distance_um_for_reflection_finding = 3000
step_after_finding_reflection_um = 10
n_bg_images_for_reflection_finding = 10
max_scan_distance_um = 3000
