[eye_tracker]
sleep = false
binary_threshold_left = 20
binary_threshold_right = 20
roi_left_center_xy = [
    500,
    500,
]
roi_left_width_height = [
    100,
    100,
]
roi_right_center_xy = [
    500,
    500,
]
roi_right_width_height = [
    100,
    100,
]
apply_roi = true
save_images_path = ""
max_saving_freq_hz = 5
save_images = false
do_ellipse_fitting = true
overlay_ellipse = true
frame_returned = "original"
