[eye_tracker]
sleep = false
binary_threshold_left = 20
binary_threshold_right = 20
save_images_path = ""
max_saving_freq_hz = 5
save_images = false
do_ellipse_fitting = true
overlay_ellipse = true
frame_returned = "original"
