[global]
pixel_offset_left = 1
pixel_offset_right = 0
selected_rows = [
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
]

[sample]
prominence_fraction = 0.05
min_peak_width = 1
min_peak_height = 5
rel_height = 0.5
wlen_pixels = 10
fitting_model = "lorentzian"

[reference]
prominence_fraction = 0.05
min_peak_width = 1
min_peak_height = 1000
rel_height = 0.5
wlen_pixels = 40
fitting_model = "lorentzian"
