[calibration]
n_per_freq = 20
calibration_freqs = [
    4.0,
    4.25,
    4.5,
    4.75,
    5.0,
    5.25,
    5.5,
    5.75,
    6.0,
    6.25,
    6.5,
    6.75,
    7.0,
    7.25,
    7.5,
    7.75,
    8.0,
    8.25,
    8.5,
    8.75,
    9.0,
]
reference = "distance"

[find_peaks.sample]
prominence_fraction = 0.05
min_peak_width = 1
min_peak_height = 5
rel_height = 0.5
wlen_pixels = 10

[find_peaks.reference]
prominence_fraction = 0.05
min_peak_width = 1
min_peak_height = 1000
rel_height = 0.5
wlen_pixels = 40

[andor_frame]
selected_rows = [
    4,
    5,
    6,
    7,
    8,
    9,
]
n_dark_images = 100
take_dark_image = false
n_bg_images = 10
x_start = 45
x_end = 110
y_start = 300
y_end = 315
vbin = 1
hbin = 1
amp_mode_index = 16
