[calibration]
n_per_freq = 10
calibration_freqs = [
    5.0,
    5.5,
    6.0,
    6.5,
    7.0,
    7.5,
    8.0,
]
reference = "distance"

[andor_camera.sample]
exposure_time = 1
gain = 1

[sline]
selected_rows = [
    4,
    5,
    6,
    7,
    8,
    9,
    10,
]

[find_peaks.sample]
prominence_fraction = 0.05
min_peak_width = 1
min_peak_height = 200
rel_height = 0.5
wlen_pixels = 10

[find_peaks.reference]
prominence_fraction = 0.05
min_peak_width = 1
min_peak_height = 1000
rel_height = 0.5
wlen_pixels = 40
