[calibration]
n_per_freq = 3
calibration_freqs = [
    5.0,
    5.2,
    5.4,
    5.6,
    5.8,
]
reference = "distance"

[andor_camera.sample]
exposure_time = 1
gain = 1

[sline]
selected_rows = [
    9,
    10,
    11,
    12,
]

[find_peaks.sample]
prominence_fraction = 0.05
min_peak_width = 2
min_peak_height = 100
rel_height = 0.5
wlen_pixels = 30

[find_peaks.reference]
prominence_fraction = 0.05
min_peak_width = 2
min_peak_height = 100
rel_height = 0.5
wlen_pixels = 30
