[calibration]
degree = 1
n_per_freq = 100
calibration_freqs = [
    4.0,
    4.25,
    4.5,
    4.75,
    5.0,
    5.25,
    5.5,
    5.75,
    6.0,
    6.25,
    6.5,
    6.75,
    7.0,
    7.25,
    7.5,
    7.75,
    8.0,
]
reference = "distance"

[find_peaks.sample]
prominence_fraction = 0.05
min_peak_width = 1
min_peak_height = 5
rel_height = 0.5
wlen_pixels = 10
fitting_model = "lorentzian"

[find_peaks.reference]
prominence_fraction = 0.05
min_peak_width = 1
min_peak_height = 1000
rel_height = 0.5
wlen_pixels = 40
fitting_model = "gaussian"

[andor_frame]
selected_rows = [
    4,
    5,
    6,
    7,
    8,
    9,
]
n_dark_images = 10
take_dark_image = true
n_bg_images = 10
x_start = 45
x_end = 110
y_start = 300
y_end = 315
vbin = 1
hbin = 1
n_px_crop_left_side = 0
n_px_crop_right_side = 0
pre_amp_mode = 16
vss_index = 4
flip_image_horizontally = true
