[calibration]
n_per_freq = 10
calibration_freqs = [
    5.0,
    5.05,
    5.1,
    5.15,
    5.2,
    5.25,
    5.3,
    5.35,
    5.4,
    5.45,
    5.5,
]
reference = "distance"

[find_peaks.sample]
prominence_fraction = 0.05
min_peak_width = 1
min_peak_height = 50
rel_height = 0.5
wlen_pixels = 10


[find_peaks.reference]
prominence_fraction = 0.05
min_peak_width = 1
min_peak_height = 1000
rel_height = 0.5
wlen_pixels = 40


[andor_frame]
selected_rows = [
    4,
    5,
    6,
    7,
    8,
    9,
    10,
]
n_dark_images = 10
take_dark_image = true
n_bg_images = 10
x_start = 45
x_end = 110
y_start = 300
y_end = 315
vbin = 1
hbin = 1
amp_mode_index = 18
