[calibration]
degree = 2
n_per_freq = 3
calibration_freqs = [
    4.0,
    4.25,
    4.5,
    4.75,
    5.0,
]
reference = "distance"

[find_peaks.sample]
prominence_fraction = 0.05
min_peak_width = 1
min_peak_height = 5
rel_height = 0.5
wlen_pixels = 10
fitting_model = "lorentzian"

[find_peaks.reference]
prominence_fraction = 0.05
min_peak_width = 1
min_peak_height = 1000
rel_height = 0.5
wlen_pixels = 40
fitting_model = "gaussian"

[andor_frame]
selected_rows = [
    4,
    5,
    6,
    7,
    8,
    9,
]
n_dark_images = 10
take_dark_image = true
n_bg_images = 10
x_start = 45
x_end = 110
y_start = 300
y_end = 315
vbin = 1
hbin = 1
amp_mode_index = 16
