[calibration]
n_per_freq = 10
calibration_freqs = [
    5.0,
    5.5,
    6.0,
    6.5,
    7.0,
    7.5,
    8.0,
]
reference = "distance"

[find_peaks.sample]
prominence_fraction = 0.05
min_peak_width = 1
min_peak_height = 200
rel_height = 0.5
wlen_pixels = 10
bg_model = "no model"

[find_peaks.reference]
prominence_fraction = 0.05
min_peak_width = 1
min_peak_height = 1000
rel_height = 0.5
wlen_pixels = 40
bg_model = "no model"

[andor_frame]
selected_rows = [
    4,
    5,
    6,
    7,
    8,
    9,
    10,
]
n_dark_images = 10
do_subtract_dark_image = false
n_bg_images = 5
x_start = 40
x_end = 120
y_start = 300
y_end = 315
vbin = 1
hbin = 1
amp_mode_index = 18
