[sline]
selected_rows = [
    8,
    9,
    10,
]

[find_peaks.sample]
prominence_fraction = 0.05
min_peak_width = 2
min_peak_height = 200
rel_height = 0.5
wlen_pixels = 30

[find_peaks.reference]
prominence_fraction = 0.05
min_peak_width = 2
min_peak_height = 100
rel_height = 0.5
wlen_pixels = 30
