[left]
id = "DEV_000F315BC084"
offset_x = 500
offset_y = 500
width = 1000
height = 1000
gain = 0
exposure = 119275
gamma = 1.0

[right]
id = "DEV_000F315BC0A5"
offset_x = 500
offset_y = 500
width = 1000
height = 1000
gain = 0
exposure = 134565
gamma = 1.0
