[left]
id = "DEV_000F315BC084"
offset_x = 0
offset_y = 0
width = 1024
height = 768
gain = 12.0
exposure = 20000.0
gamma = 1.0

[right]
id = "DEV_000F315BC0A5"
offset_x = 0
offset_y = 0
width = 1024
height = 768
gain = 12.0
exposure = 20000.0
gamma = 1.0
