[left]
id = "DEV_000F315BC084"
offset_x = 100
offset_y = 500
width = 1000
height = 500
gain = 12
exposure = 20000
gamma = 1.0

[right]
id = "DEV_000F315BC0A5"
offset_x = 0
offset_y = 0
width = 1024
height = 768
gain = 21
exposure = 73404
gamma = 1.0
