[left]
id = "DEV_000F315BC084"
offset_x = 500
offset_y = 500
width = 1000
height = 1000
gain = 7
exposure = 201843
gamma = 1.01

[right]
id = "DEV_000F315BC0A5"
offset_x = 500
offset_y = 500
width = 1000
height = 1000
gain = 7
exposure = 214075
gamma = 1.0
